services:
  llmops-ui:
    image: llmops-ui:0.1.0
    build:
      context: ../ui
      dockerfile: Dockerfile
    container_name: llmops-ui
    restart: always
    environment: []
    ports:
      - "3000:3000"
  llmops-api:
    image: llmops-api:0.1.0
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: llmops-api
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      # 模式为API 代表启用API服务
      MODE: api
      SERVER_WORKER_AMOUNT: 4
      SERVER_THREAD_AMOUNT: 4
      # 数据库迁移配置
      MIGRATION_ENABLED: 'true'
      # JWT加密密钥
      JWT_SECRET_KEY: Xzw3R1sIdCVALL0n2khomN8jiHY6EutX
      # CSRF校验开关
      WTF_CSRF_ENABLED: 'false'
      # SQLAlchemy数据库配置
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:PASSWORD@llmops-db:5432/llmops?client_encoding=utf8
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'
      # Redis缓存数据库配置
      REDIS_HOST: llmops-redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: PASSWORD
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'
      # Weaviate向量数据库配置
      WEAVIATE_HTTP_HOST: llmops-weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: llmops-weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ftBC9hKkjfdbdi0W3T6kEtMh5BZFpGa1DF8
      # 腾讯云COS对象存储
      COS_SECRET_ID: ID
      COS_SECRET_KEY: your_api_key
      COS_REGION: ap-beijing
      COS_SCHEME: https
      COS_BUCKET: Name
      COS_DOMAIN: ''
      # Celery配置
      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'
      # Github OAuth应用密钥
      GITHUB_CLIENT_ID: ID
      GITHUB_CLIENT_SECRET: your_api_key
      GITHUB_REDIRECT_URI: http://your_domain/auth/authorize/github
      # LangSmith配置
      LANGCHAIN_TRACING_V2: 'true'
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_API_KEY: your_api_key
      LANGCHAIN_PROJECT: PROJECT_NAME
      # 设置HuggingFace强制离线
      TRANSFORMERS_OFFLINE: 1
      # 辅助Agent智能体应用id标识
      ASSISTANT_AGENT_ID: 6774fcef-b594-8008-b30c-a05b8190afe6
      # OpenAI model
      OPENAI_API_KEY: your_api_key
      OPENAI_API_BASE: url
      # 百度千帆服务提供者
      qianfan_ak: your_api_key
      qianfan_sk: your_api_key
      # 月之暗面服务提供者
      MOONSHOT_API_KEY: your_api_key
      # 通义千问
      DASHSCOPE_API_KEY: your_api_key
      # 文心一言
      WENXIN_YIYAN_API_KEY: your_api_key
      # DeepSeek API 配置
      DEEPSEEK_API_KEY: your_api_key
      DEEPSEEK_API_BASE: https://api.deepseek.com/v1
      # 高德API
      GAODE_API_KEY: your_api_key
      # 谷歌serper搜索
      SERPER_API_KEY: your_api_key
    ports:
      - "5001:5001"
    depends_on:
      - llmops-db
      - llmops-redis
      - llmops-weaviate
  llmops-celery:
    image: llmops-api:0.1.0
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: llmops-celery
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      # 模式为Celery 代表启用Celery异步任务队列
      MODE: celery
      CELERY_WORKER_AMOUNT: 4
      # 数据库迁移配置
      MIGRATION_ENABLED: 'false'
      # JWT加密密钥
      JWT_SECRET_KEY: Xzw3R1sIdCVALL0n2khomN8jiHY6EutX
      # CSRF校验开关
      WTF_CSRF_ENABLED: 'false'
      # SQLAlchemy数据库配置
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:PASSWORD@llmops-db:5432/llmops?client_encoding=utf8
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'
      # Redis缓存数据库配置
      REDIS_HOST: llmops-redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: PASSWORD
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'
      # Weaviate向量数据库配置
      WEAVIATE_HTTP_HOST: llmops-weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: llmops-weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ftBC9hKkjfdbdi0W3T6kEtMh5BZFpGa1DF8
      # 腾讯云COS对象存储
      COS_SECRET_ID: ID
      COS_SECRET_KEY: your_api_key
      COS_REGION: ap-beijing
      COS_SCHEME: https
      COS_BUCKET: name
      COS_DOMAIN: ''
      # Celery配置
      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'
      # Github OAuth应用密钥
      GITHUB_CLIENT_ID: ID
      GITHUB_CLIENT_SECRET: your_api_key
      GITHUB_REDIRECT_URI: http://your_domain/auth/authorize/github
      # LangSmith配置
      LANGCHAIN_TRACING_V2: 'true'
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_API_KEY: your_api_key
      LANGCHAIN_PROJECT: PROJECT_NAME
      # 设置HuggingFace强制离线
      TRANSFORMERS_OFFLINE: 1
      # 辅助Agent智能体应用id标识
      ASSISTANT_AGENT_ID: 6774fcef-b594-8008-b30c-a05b8190afe6
      # OpenAI model
      OPENAI_API_KEY: your_api_key
      OPENAI_API_BASE: url
      # 百度千帆服务提供者
      qianfan_ak: your_api_key
      qianfan_sk: your_api_key
      # 月之暗面服务提供者
      MOONSHOT_API_KEY: sk-your_api_key
      # 通义千问
      DASHSCOPE_API_KEY: sk-your_api_key
      # 文心一言
      WENXIN_YIYAN_API_KEY: your_api_key
      # DeepSeek API 配置
      DEEPSEEK_API_KEY: sk-your_api_key
      DEEPSEEK_API_BASE: https://api.deepseek.com/v1
      # 高德API
      GAODE_API_KEY: your_api_key
      # 谷歌serper搜索
      SERPER_API_KEY: your_api_key
    depends_on:
      - llmops-db
      - llmops-redis
      - llmops-weaviate
  llmops-redis:
    image: redis:6-alpine
    restart: always
    container_name: llmops-redis
    volumes:
      - ./volumes/redis/data:/data
    # 启动redis服务时配置
    command: redis-server --requirepass PASSWORD
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    ports:
      - "6379:6379"
  llmops-db:
    image: postgres:15-alpine
    restart: always
    container_name: llmops-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: llmops
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # 将postgres数据挂载到本地 ./volumes/db/data上
      - ./volumes/db/data:/var/lib/postgresql/data/pgdata
      # 初始化脚本只有再空数据挂载下才会触发执行(.sql/.sh等) 如果已经存在数据则不会执行
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"
  llmops-weaviate:
    image: semitechnologies/weaviate:1.28.4
    container_name: llmops-weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25  # 查询默认返回的数据条数
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'  # 需要授权才能和weaviate进行交互
      PERSISTENCE_DATA_PATH: /var/lib/weaviate  # weaviate数据存储路径
      DEFAULT_VECTORIZER_MODEL: 'none'  # 向量化模块设置为none
      CLUSTER_HOSTNAME: 'node1'  # 节点的主机名字
      AUTHENTICATION_APIKEY_ENABLED: 'true'  # 启动基于API密钥的身份校验
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'ftBC9hKkjfdbdi0W3T6kEtMh5BZFpGa1DF8'  # 允许的API密钥列表
      AUTHENTICATION_APIKEY_USERS: 'your_email@example.com'  # 基于密钥的API身份列表
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'  # 启动AdminList授权方案
      AUTHORIZATION_ADMINLIST_USERS: 'your_email@example.com'  # 使用AdminList方案时具有管理权限的用户
    volumes:
      - ./volumes/weaviate:/var/lib/weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
  llmops-nginx:
    image: nginx:latest
    restart: always
    container_name: llmops-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - llmops-ui
      - llmops-api
    ports:
      - "80:80"